name: Docker Image CI

on:
  push:
    branches: 
    - 'main'
    - 'dev'

jobs:

  build_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Verify Dockerfile changed
      id: dockerfile_changed
      uses: tj-actions/changed-files@v18.7
      with:
        files: |
          docker/stan/Dockerfile
      
    - name: Login to DockerHub
      if: steps.dockerfile_changed.outputs.any_changed == 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push the Docker image
      if: steps.dockerfile_changed.outputs.any_changed == 'true'
      run: |
        docker build -f docker/stan/Dockerfile -t vntasis/stan:${{ github.ref_name }} .
        docker push vntasis/stan:${{ github.ref_name }}
        if [ ${{ github.ref_name }} == 'main' ]
        then
          docker tag vntasis/stan:${{ github.ref_name }} vntasis/stan:latest
          docker push vntasis/stan:latest
        fi
